### ISSUE TITLE
Firing up Jetty App runs unit tests, despite -Dmaven.test.skip=true...!

### ISSUE THREAD

**Issue by epugh** [MedKhem/grobid-dictionaries#30]
I'm using Maven 3.6, and when I run:

```
 mvn -Dmaven.test.skip=true jetty:run-war
```
All the unit tests are run!   However:

```
mvn -DskipTests jetty:run-war 
```

works as expected.  

According to http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skip the `maven.test.skip` isn't recommended, and the solution is to use the http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skipTests parameter, ie `-DskipTests`.   I think this could be just a simple documentation fix, and happy to submit a PR for that.   

Or I can dig more into the surefire plugin configuration...

**Comment by MedKhem** [comment]
I've just fixed it for the dev docs and Docker instructions. Thanks for the help!

**Comment by epugh** [comment]
Saw the fix, thanks.
