### ISSUE TITLE
Some adjustment to the demo part

### ISSUE THREAD

**Issue by lfoppiano** [MedKhem/grobid-dictionaries#8]
The demo part is a bit confusing IMHO: 
 1. the selection `Process Dictionary` should be something equivalent ot the grobid `process fulltext`, the application of all cascade models to label and extract information from a dictionary. 
 2. The other selection could be used for debugging, to see visually what each model is doing. 

<img width="995" alt="screen shot 2017-05-08 at 08 33 44" src="https://cloud.githubusercontent.com/assets/15426/25792838/61da2036-33c9-11e7-8ac5-ffc705c3a878.png">

My 2 cents 🍡

**Comment by MedKhem** [comment]
Well, I agree with you that the name "Dictionary" is a bit confusing. But if you want an exact analogy with GROBID, then I would suggest to have "process fullDictionary" to run in cascade all the existing models. What do suggest as a replacement for "Process Dictionary"? 

Thank you for the special price :D

**Comment by lfoppiano** [comment]
Like in GROBID, there should be the default `Process Dictionary` that, using all available models process the dictionary. 

Secondly you can have:
 1. reusable models (for example the date model) or
 2. the cascade models (for debug reasons) - I'm not sure they are needed in the demo.
